openapi: 3.0.0
info:
  title: Blackthorn Event Registration API
  description: Be the change you wish to see in the world
  version: 0.1.0
servers:
  - url: /api
    description: this
  - url: http://localhost:43200/api
    description: dev
  - url: https://stark-badlands-90167.herokuapp.com/api
    description: staging
  - url: https://polar-beach-61154.herokuapp.com/api
    description: production
components:
  schemas:
    Error:
      type: object
      properties:
        status:
            type: number
            example: 400
        message:
            type: string
            example: Bad request
    BadRequestError:
      type: object
      properties:
        status:
            type: number
            example: 400
        message:
            type: string
            example: Bad request
    NotFoundError:
      type: object
      properties:
        status:
            type: number
            example: 404
        message:
            type: string
            example: Not found
    Attendee:
      type: object
      properties:
        first_name: 
          type: string
          maxLength: 64
        last_name:
          type: string
          maxLength: 64
        email: 
          type: string
          maxLength: 64
          pattern: '(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)'
        phone:
          type: string
          maxLength: 32
        company:
          type: string
          maxLength: 128
        ticket:
          type: integer
        sessions:
          type: array
          items:
            type: integer
    EventDetail:
      type: object
      properties:
        name: 
          type: string
          maxLength: 64
        description: 
          type: string
        time_start:
          type: string
        time_end:
          type: string
        contact_email:
          type: string
        contact_phone:
          type: string
        location_name:
          type: string
        location_address:
          type: string
        status:
          type: string
        tickets:
          type: array
          items:
            type: objects
            properties:
              label:
                type: string
              description:
                type: string
              price:
                type: number
                multipleOf: 0.01
                minimum: 0.00
                maximum: 999,999,999.99
              status:
                type: string
                enum: [ "open", "sold out" ]
        sessions:
          type: array
          items:
            type: object
            properties:
              label:
                type: string
              description:
                type: string
              price:
                type: number
                multipleOf: 0.01
                minimum: 0.00
                maximum: 999,999,999.99
              status:
                type: string
                enum: [ "open", "sold out" ]
    EventList:
      type: array
      items: 
        type: object
        properties:
          id:
            type: integer
          name: 
            type: string
            maxLength: 64
          description: 
            type: string
          time_start:
            type: string
          time_end:
            type: string
          status:
            type: string
            enum: [ "open", "sold out" ]
paths:
  /ping:
    get:
      summary: Ping Pong
      tags: [ ping ]
      responses:
        '200':
          description: Everything is OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                    example: pong
  /events:
    get:
      summary: Returns a list of events
      tags: [ events ]
      responses:
        '200':
          description: A JSON array of event objects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventList'
              example:
                - id: 1
                  name: "Yoga Retreat"
                  description: "<p>Yoga at the lake</p>"
                  time_start: "2021-10-15 08:00:00"
                  time_end: "2021-10-15 20:00:00"
                  status: "open"
                - id: 2
                  name: "Tribal Symposium"
                  description: "<p>Inter-tribal workshops</p>"
                  time_start: "2021-10-15 08:00:00"
                  time_end: "2021-10-15 20:00:00"
                  status: "sold out"

  /events/{id}:
    get:
      summary: Returns an event by ID
      tags: [ events ]
      parameters:
        - name: id
          in: path
          required: true
          description: Event ID
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventDetail'
              example:
                id: 1
                name: Tribal Symposium
                description: "<p>Inter-tribal workshops</p>"
                time_start: "2021-10-15 08:00:00"
                time_end: "2021-10-15 20:00:00"
                location_name: "Some Remote Place"
                location_address: "The Carribean, Central America"
                contact_email: "tribalsymposium@geemail.com"
                contact_phone: "(555) 555 5555"
                status: "open"
                tickets:
                  - id: 1
                    label: Free
                    description: General admission
                    price: 0.00
                    status: open
                sessions:
                  - id: 1
                    label: Chocolate Cultivation
                    description: Learn to farm, harvest, and process chocolate using organic practices and traditional tools
                    price: 0.00
                    status: open
                  - id: 2
                    label: Hammock Weaving
                    description: Learn to weave hammocks using a traditional loom and hand rolled cotton fiber
                    price: 0.00
                    status: open
                  - id: 3
                    label: Mascaras Diablos (carving)
                    description: Learn to carve traditional Boruca masks from balsa wood
                    price: 0.00
                    status: open
                  - id: 4
                    label: Mascaras Diablos (painting)
                    description: Learn to paint traditional Boruca masks
                    price: 0.00
                    status: sold out
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
  /events/{id}/register:
    post:
      summary: Register for an event
      tags: [ events ]
      parameters:
        - name: id
          in: path
          required: true
          description: Event ID
          schema:
            type: integer
            minimum: 1
      requestBody:
        description: Event registration with attendee, ticket, and session information
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                attendees:
                  type: array
                  items: 
                    $ref: "#/components/schemas/Attendee"
              example:
                attendees:
                  - first_name: "Dahlia"
                    last_name: "Antunez"
                    email: "dahlia.antunez@geemail.com"
                    phone: "(555) 555-5555"
                    company: "Fly Industries"
                    ticket: 4
                    sessions: [ 1, 2 ]
                  - first_name: "Artur"
                    last_name: "Janssen"
                    email: "artur.janssen@geemail.com"
                    phone: "(555) 555-5555"
                    company: ""
                    ticket: 3
                    sessions: [ 1, 3 ]
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: integer
                    example: 1
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
